name: flutter_chips_input_sunny
author: Danvick Miller <danvickmiller@gmail.com>
version: 2.2.0
homepage: https://github.com/danvick/flutter_chips_input
description: Flutter library for building input fields with InputChips as input options.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  after_layout: ^1.1.0
  collection_diff: ^2.0.3+5
  logging: ^1.0.0
  observable_collections: ^0.7.0+1
  stream_transform: ^2.0.0
  sunny_dart: ^0.9.0+1
  flutter: 
    sdk: flutter
dev_dependencies: 
  logging_config: ^0.6.7+6
  flutter_test: 
    sdk: flutter
flutter: null
