name: flutter_chips_input_sunny
description: Flutter library for building input fields with InputChips as input options.
version: 2.2.0-nullsafety.1
author: Danvick Miller <danvickmiller@gmail.com>
homepage: https://github.com/danvick/flutter_chips_input

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  after_layout: ^1.1.0
  collection_diff: ^2.0.3+5
  flutter:
    sdk: flutter
  logging: ^1.0.0
  observable_collections: ^0.6.1-nullsafety.6
  stream_transform: ^2.0.0
  sunny_dart: ^0.8.2+2

dev_dependencies:
  logging_config: ^0.6.7+6
  flutter_test:
    sdk: flutter

dependency_overrides:
#  sunny_dart:
#    path: ../sunny_dart
#  collection_diff:
#    path: ../collection_diff
#  observable_collections:
#    path: ../observable_collections

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
